Implemented claim button
swayprotocol/creator-pools pull request #13
Opened 2022-02-02 10:26 UTC by mayki0909

https://app.clickup.com/t/244fwfq

2022-02-02 15:18 UTC, matjaz-NFT requested changes
how difficult would be, to create separate modals, so we don't have ton of if statements in one file?

2022-02-02 15:18 UTC, matjaz-NFT commented on components/Modal/index.tsx
> +      props.onClose(true);
is data refreshed in main page after close (claim button hidden)?

2022-02-02 15:18 UTC, matjaz-NFT commented on components/Stakes/Positions.tsx
> +    console.log(reward)
remove console.log

2022-02-02 15:18 UTC, matjaz-NFT commented on components/Stakes/Positions.tsx
> +    setReward(parseFloat(reward))
what happens if request fails?

2022-02-03 09:50 UTC, mrVers commented on components/Modal/index.tsx
> +      props.onClose(true);
The `true` in the `onClose()` function fires the reload in the parent element.

2022-02-03 10:31 UTC, mrVers requested changes

2022-02-03 10:31 UTC, mrVers commented on components/Modal/index.tsx
> +              (<form onSubmit={formSubmit}>
I'm confused how this works, since you have `props.modalData.type !== ModalType.CLAIM ` above and below, `props.modalData.type === ModalType.CLAIM`.

I guess `reward !== 0` would keep the same effect, but for readability, this should be updated to 
`(props.modalData.type !== ModalType.CLAIM || props.modalData.type === ModalType.CLAIM && reward)`

2022-02-03 10:31 UTC, mrVers commented on components/Modal/index.tsx
> +                      </span>
<img width="413" alt="Screenshot 2022-02-03 at 11 09 06" src="https://user-images.githubusercontent.com/17031093/152322249-f6f3b1f9-e2e1-4ebb-b2c7-c202b7851695.png">
Visual, there a 10px space missing.

2022-02-03 10:31 UTC, mrVers commented on components/Modal/index.tsx
> +                {(props.modalData.type === ModalType.STAKE || props.modalData.type === ModalType.UNSTAKE || props.modalData.type === ModalType.ADD) && (
There are a couple of exact consecutive  `if` function:
`{(props.modalData.type === ModalType.STAKE || props.modalData.type === ModalType.UNSTAKE || props.modalData.type === ModalType.ADD) && (`
One here, one at line 292.

Please use just one `if` and add all the the html in between.

2022-02-03 10:31 UTC, mrVers commented on components/Modal/index.tsx
> +                {(props.modalData.type === ModalType.STAKE || props.modalData.type === ModalType.UNSTAKE || props.modalData.type === ModalType.ADD) && (
You can wrap them in `<></>`

2022-02-03 10:31 UTC, mrVers commented on components/Modal/index.tsx
> +                    {(props.modalData.type !== ModalType.UNSTAKE && props.modalData.type !== ModalType.CLAIM) && (
`props.modalData.type === ModalType.STAKE || props.modalData.type === ModalType.ADD`

2022-02-03 10:31 UTC, mrVers commented on components/Stakes/Positions.tsx
> +    setReward(parseFloat(reward))
The rewards is has an initial value of `0`, so if the request fails, the user won't be able to claim.
We could put it in a try/catch function, but as i see, i have a couple of similar requests without try/catch and so far no issues..

2022-02-03 10:31 UTC, mrVers commented on components/Stakes/Positions.tsx
> +              <button className="btn btn-secondary" onClick={() => openStakeModal(ModalType.CLAIM, reward.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 }))}>
`reward.toLocaleString()` is for formatting, e.g `1000.23`, is returned as `1,000.23`. 
In this case .toString() would be better, since it's what you need.

2022-02-10 12:18 UTC, mrVers approved these changes

2022-02-14 11:20 UTC, matjaz-NFT approved these changes

2022-02-14 11:20 UTC, merged